Fixes to get piedpiper installer working on DO Ubuntu 18.04
AFCYBER-DREAM/ansible-collection-pidev pull request #3
Opened 2019-05-01 20:20 UTC by dingus9

2019-05-02 01:12 UTC, ragingpastry commented
#nitpick commit messages!

https://chris.beams.io/posts/git-commit/

2019-05-02 15:21 UTC, codrcodz reviewed
Your .gitignore changes conflict with previous PR.

2019-05-02 15:22 UTC, codrcodz requested changes
Please resolve merge conflicts to .gitignore.

2019-05-03 02:54 UTC, dingus9 commented
Merge conflicts fixed, I did chose to leave the ansible driver in for now so that I can push configs... the pull method doesn't let me deploy from local changes. I will test the pull method again once these changes are merged in. Pull method pulls from master after all.

2019-05-03 19:49 UTC, codrcodz requested changes

2019-05-03 19:49 UTC, codrcodz commented on bootstrap.sh
> -which pip3 || curl -s https://bootstrap.pypa.io/get-pip.py | python3.6;
get-pip is now the canonical method for installing pip according to the PyPA and ensures the user is always installing pacakges with the latest version of pip.

2019-05-03 19:49 UTC, codrcodz commented on bootstrap.sh
> +  && apt-get install -y python3-pip;
use get-pip to perform initial install of pip, and pip itself to upgrade pip thereafter.

2019-05-03 19:49 UTC, codrcodz commented on bootstrap.sh
> -which pip3 || curl -s https://bootstrap.pypa.io/get-pip.py | python3.6;
Also, by removing this line, you would break the minishift env.

2019-05-07 18:43 UTC, merged